title: "Instagram Downloader"
email: "obvious.ly.dev@gmail.com"
description: "A Python script to download content from Instagram without account."
baseurl: "/instagram-downloader" # The subpath of the website
url: "https://ximaz.github.io"   # The base hostname and protocol
twitter_username: "_Ximaz"
github_username: "Ximaz"

# Build settings
markdown: "kramdown"
theme: jekyll-theme-hacker
plugins:
  - jykyll-feed
